# if the application does not need a build stage, the entire build: section can be omitted
build:

  # the image to use when building the code (should have any required build tools like the JDK)
  image: amazoncorretto:21-alpine-jdk

  # #if your tests require a throwaway database or other process it can be run as a "sidecar" container
  # these sidecar containers are linked to the build container with the specified name,
  # so for example you can access the redis container below at http://redis:6379 (default port)
  # sidecars:
  ## the list of steps to run inside the build container
  # for a gradle project this will often just be one step as shown below
  steps:
    - ./gradlew clean build --refresh-dependencies --stacktrace
containerBuild:
  imageName: tfidentity/cdc-account-management

deployment:
  name: cdc-account-management
  namespace: tfidentity
  cpu: 100m
  memory: 2Gi
  replicas: 1
  containerPort: 8080
  healthCheckPath: /cdcam/actuator/health
  healthCheckPort: 8080 #management port
  ingressPath: /cdcam
  iamRole: cdcam-execution-role
  labels:
    component: backend
    stack: java
    sub_application: cdc-account-management
    part_of: Identity-login
    stack_version: 21
    namespace: tfidentity
  volumeMounts:
    - name: cdcam-config
      mountPath: /etc/config
      connectionString: "configMap|name: cdcam-config"
  #startupSeconds: 180

environments:
  qa4:
    branch: integration-corp/v1
    promotion:
      to: qa
      mergeTo: release-corp/v1
    cluster: tfcom-eks-na-identity-qa1.identityqa.thermofisher.net
    env:
      - name: spring.profiles.active
        value: qa4
      - name: SPRING.PROFILES.ACTIVE
        value: qa4
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config-qa4.yml
    deployment:
      replicas: 1
      name: cdc-account-management-qa4
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - tfcom-api-eks-identity-qa4.identityqa.thermofisher.net
  qa4-cn:
    branch: integration-corp/v1
    promotion:
      to: qa1-cn
      mergeTo: release-corp/v1
    cluster: tfcom-cluster-cn-apac.clouddev.thermofisher.net.cn
    env:
      - name: spring.profiles.active
        value: qa4-cn
      - name: SPRING.PROFILES.ACTIVE
        value: qa4-cn
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config.yml
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam.tfcom-cluster-cn-apac.clouddev.thermofisher.net.cn
  qa1:
    branch: release-corp/v1
    promotion:
      to: prod
      mergeTo: master
    cluster: tfcom-eks-na-identity-qa1.identityqa.thermofisher.net
    env:
      - name: spring.profiles.active
        value: qa1
      - name: SPRING.PROFILES.ACTIVE
        value: qa1
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config-qa1.yml
    deployment:
      replicas: 1
      name: cdc-account-management-qa1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - tfcom-api-eks-identity-qa1.identityqa.thermofisher.net
  qa1-cn:
    branch: release-corp/v1
    cluster: tfcom-cluster-cn-apac-qa.cloudqa.thermofisher.net.cn
    env:
      - name: spring.profiles.active
        value: qa1-cn
      - name: SPRING.PROFILES.ACTIVE
        value: qa1-cn
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config-qa1.yml
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam.tfcom-cluster-cn-apac-qa.cloudqa.thermofisher.net.cn
    promotion:
      to: prod-cn
      mergeTo: master
  prod:
    branch: master
    cluster: tfcom-cluster-na-prodb.cloud.thermofisher.net
    env:
      - name: spring.profiles.active
        value: prod
      - name: SPRING.PROFILES.ACTIVE
        value: prod
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config.yml
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 4
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam.tfcom-cluster-na-prodb.cloud.thermofisher.net
  prod-cn:
    branch: master
    cluster: tfcom-cluster-cn-apac-prod.cloudprod.thermofisher.net.cn
    env:
      - name: spring.profiles.active
        value: prod-cn
      - name: SPRING.PROFILES.ACTIVE
        value: prod-cn
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config.yml
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 4
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam.tfcom-cluster-cn-apac-prod.cloudprod.thermofisher.net.cn
  stage:
    branch: stage/.*
    cluster: tfcom-cluster-na-qa1.cloudqa.thermofisher.net
    env:
      - name: spring.profiles.active
        value: stage
      - name: SPRING.PROFILES.ACTIVE
        value: stage
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config-stage.yml
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam-stage.tfcom-cluster-na-qa1.cloudqa.thermofisher.net
      - cdcam.stage.cloudqa.thermofisher.net
  stage-cn:
    branch: stage/.*
    cluster: tfcom-cluster-cn-apac-qa.cloudqa.thermofisher.net.cn
    env:
      - name: spring.profiles.active
        value: stage-cn
      - name: SPRING.PROFILES.ACTIVE
        value: stage-cn
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config-stage.yml
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam-stage.tfcom-cluster-cn-apac-qa.cloudqa.thermofisher.net.cn