build:
  image: maven:3.8.3-openjdk-17
  steps:
    - mvn clean package -U

containerBuild:
  imageName: cdcam/cdc-account-management

deployment:
  name: cdc-account-management
  namespace: cdcam
  cpu: 100m
  memory: 2Gi
  replicas: 1
  containerPort: 8080
  healthCheckPath: /cdcam/actuator/health
  healthCheckPort: 8080 #management port
  ingressPath: /cdcam
  iamRole: cdcam-execution-role
  volumeMounts:
    - name: cdcam-config
      mountPath: /etc/config
      connectionString: "configMap|name: cdcam-config"
  #startupSeconds: 180

environments:
  qa4:
    branch: integration/.*
    cluster: tfcom-cluster-na-qa1.cloudqa.thermofisher.net
    env:
      - name: spring.profiles.active
        value: qa4
      - name: SPRING.PROFILES.ACTIVE
        value: qa4
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config-qa4.yml
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam-qa4.tfcom-cluster-na-qa1.cloudqa.thermofisher.net
  
  qa4-cn:
    branch: integration/.*
    cluster: tfcom-cluster-cn-apac.clouddev.thermofisher.net.cn
    env:
      - name: spring.profiles.active
        value: qa4-cn
      - name: SPRING.PROFILES.ACTIVE
        value: qa4-cn
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config.yml
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam.tfcom-cluster-cn-apac.clouddev.thermofisher.net.cn

  qa1-cn:
    branch: release/.*
    cluster: tfcom-cluster-cn-apac-qa.cloudqa.thermofisher.net.cn
    env:
      - name: spring.profiles.active
        value: qa1-cn
      - name: SPRING.PROFILES.ACTIVE
        value: qa1-cn
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config-qa1.yml
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam.tfcom-cluster-cn-apac-qa.cloudqa.thermofisher.net.cn
    promotion:
      to: prod-cn
      mergeTo: master

  qa1:
    branch: release/.*
    cluster: tfcom-cluster-na-qa1.cloudqa.thermofisher.net
    env:
      - name: spring.profiles.active
        value: qa1
      - name: SPRING.PROFILES.ACTIVE
        value: qa1
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config-qa1.yml
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam-qa1.tfcom-cluster-na-qa1.cloudqa.thermofisher.net
    promotion:
        to: prod
        mergeTo: master

  stage-cn:
    branch: stage/.*
    cluster: tfcom-cluster-cn-apac-qa.cloudqa.thermofisher.net.cn
    env:
      - name: spring.profiles.active
        value: stage-cn
      - name: SPRING.PROFILES.ACTIVE
        value: stage-cn
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config-stage.yml
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam-stage.tfcom-cluster-cn-apac-qa.cloudqa.thermofisher.net.cn

  stage:
    branch: stage/.*
    cluster: tfcom-cluster-na-qa1.cloudqa.thermofisher.net
    env:
      - name: spring.profiles.active
        value: stage
      - name: SPRING.PROFILES.ACTIVE
        value: stage
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config-stage.yml
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam-stage.tfcom-cluster-na-qa1.cloudqa.thermofisher.net
      - cdcam.stage.cloudqa.thermofisher.net

  prod:
    branch: master
    cluster: tfcom-cluster-na-prodb.cloud.thermofisher.net
    env:
      - name: spring.profiles.active
        value: prod
      - name: SPRING.PROFILES.ACTIVE
        value: prod
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config.yml
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 4
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70 
    ingressDomains:
      - cdcam.tfcom-cluster-na-prodb.cloud.thermofisher.net

  prod-cn:
    branch: master
    cluster: tfcom-cluster-cn-apac-prod.cloudprod.thermofisher.net.cn
    env:
      - name: spring.profiles.active
        value: prod-cn
      - name: SPRING.PROFILES.ACTIVE
        value: prod-cn
      - name: SPRING_CONFIG_ADDITIONAL_LOCATION
        value: file:/etc/config/app-config.yml
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 4
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70 
    ingressDomains:
      - cdcam.tfcom-cluster-cn-apac-prod.cloudprod.thermofisher.net.cn
