build:
  image: maven:3-alpine
  steps:
    - mvn clean package -U

containerBuild:
  imageName: cdcam/cdc-account-management

deployment:
  name: cdc-account-management
  namespace: cdcam
  cpu: 100m
  memory: 2Gi
  replicas: 1
  containerPort: 8080
  healthCheckPath: /cdcam/actuator/health
  healthCheckPort: 8080 #management port
  ingressPath: /cdcam
  iamRole: cdcam-execution-role
  #startupSeconds: 180

environments:
  qa4:
    branch: (integration|development)/.*
    cluster: tfcom-cluster-na-qa1.cloudqa.thermofisher.net
    env:
      - name: spring.profiles.active
        value: qa4
      - name: SPRING.PROFILES.ACTIVE
        value: qa4
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam-qa4.tfcom-cluster-na-qa1.cloudqa.thermofisher.net
  
  # qa4-cn:
  #   branch: (integration|development)/.*
  #   cluster: tfcom-cluster-cn-apac.clouddev.thermofisher.net.cn
  #   env:
  #     - name: spring.profiles.active
  #       value: qa4-cn
  #     - name: SPRING.PROFILES.ACTIVE
  #       value: qa4-cn
  #   autoscaling:
  #     enabled: true
  #     minReplicas: 1
  #     maxReplicas: 2
  #     targetCPUUtilizationPercentage: 80
  #     targetMemoryUtilizationPercentage: 70
  #   ingressDomains:
  #     - cdcam.tfcom-cluster-cn-apac.clouddev.thermofisher.net.cn

  qa1-cn:
    branch: (release|qa1-test)/.*
    cluster: tfcom-cluster-cn-apac-qa.cloudqa.thermofisher.net.cn
    env:
      - name: spring.profiles.active
        value: qa1-cn
      - name: SPRING.PROFILES.ACTIVE
        value: qa1-cn
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam.tfcom-cluster-cn-apac-qa.cloudqa.thermofisher.net.cn
    promotion:
      to: prod-cn
      mergeTo: master

  qa1:
    branch: (release|qa1-test)/.*
    cluster: tfcom-cluster-na-qa1.cloudqa.thermofisher.net
    env:
      - name: spring.profiles.active
        value: qa1
      - name: SPRING.PROFILES.ACTIVE
        value: qa1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam-qa1.tfcom-cluster-na-qa1.cloudqa.thermofisher.net

  stage-cn:
    branch: stage/.*
    cluster: tfcom-cluster-cn-apac-qa.cloudqa.thermofisher.net.cn
    env:
      - name: spring.profiles.active
        value: stage-cn
      - name: SPRING.PROFILES.ACTIVE
        value: stage-cn
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam-stage.tfcom-cluster-cn-apac-qa.cloudqa.thermofisher.net.cn

  stage:
    branch: stage/.*
    cluster: tfcom-cluster-na-qa1.cloudqa.thermofisher.net
    env:
      - name: spring.profiles.active
        value: stage
      - name: SPRING.PROFILES.ACTIVE
        value: stage
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70
    ingressDomains:
      - cdcam-stage.tfcom-cluster-na-qa1.cloudqa.thermofisher.net
      - cdcam.stage.cloudqa.thermofisher.net

  prod-cn:
    branch: master
    cluster: tfcom-cluster-cn-apac-prod.cloudprod.thermofisher.net.cn
    env:
      - name: spring.profiles.active
        value: prod-cn
      - name: SPRING.PROFILES.ACTIVE
        value: prod-cn
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 4
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 70 
    ingressDomains:
      - cdcam.tfcom-cluster-cn-apac-prod.cloudprod.thermofisher.net.cn
