AWSTemplateFormatVersion: "2010-09-09"
Description: "SNS topic to post to GRP SQS for password reset."
Resources:
  AccountUpdatedTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Tags:
        - Key: name
          Value: tcm-cdc-account-management
        - Key: application
          Value: tcm-cdc-account-management
        - Key: app role
          Value: tcm-cdc-account-management
        - Key: team name
          Value: armadillos
        - Key: application owner
          Value: vijaya.paka@thermofisher.com
        - Key: costcenter
          Value: "400.8620.8582 : de platform"
        - Key: environment
          Value: nonprod
        - Key: project
          Value: tcm-cdc-account-management
        - Key: division
          Value: digital engineering
        - Key: businessunit
          Value: corporate information technology
        - Key: snow_support
          Value: de.it.dev.registration
        - Key: group
          Value: corp
        - Key: group_beneficiary
          Value: corp
        - Key: compliance
          Value: n/a
        - Key: data_classification
          Value: internal use
      TopicName:
        Fn::Sub: cdcam-notify-account-updated-${Environments}
  PasswordResetTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint:
            Fn::Sub: arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:tfgrp-pwd-reset-${Environments}
          Protocol: 'sqs'
      Tags:
        - Key: name
          Value: tcm-cdc-account-management
        - Key: application
          Value: tcm-cdc-account-management
        - Key: app role
          Value: tcm-cdc-account-management
        - Key: team name
          Value: armadillos
        - Key: application owner
          Value: vijaya.paka@thermofisher.com
        - Key: costcenter
          Value: "400.8620.8582 : de platform"
        - Key: environment
          Value: nonprod
        - Key: project
          Value: tcm-cdc-account-management
        - Key: division
          Value: digital engineering
        - Key: businessunit
          Value: corporate information technology
        - Key: snow_support
          Value: de.it.dev.registration
        - Key: group
          Value: corp
        - Key: group_beneficiary
          Value: corp
        - Key: compliance
          Value: n/a  
        - Key: data_classification
          Value: internal use
      TopicName:
        Fn::Sub: cdcam-password-reset-${Environments}
Parameters:
  Environments:
    Type: String
    Default: dev3
    AllowedValues:
      - dev3
      - qa1
      - qa4
      - qa3
      - qa5
      - stage
      - prod
    Description: Supported environments are dev3, qa1, qa4, qa3, qa5, stage and prod. Default is dev3.
