AWSTemplateFormatVersion: "2010-09-09"
Description: "Resources for the CDCAM application."

Resources:
  RegistrationTopic:
    Type: AWS::SNS::Topic
    DeletionPolicy: Retain
    Properties:
      TopicName: !Sub cdcam-notify-registration-${Environments}
      Tags:
        - Key: name
          Value: cdcam
        - Key: application
          Value: cdcam
        - Key: app role
          Value: cdcam
        - Key: team name
          Value: armadillos
        - Key: application owner
          Value: vijaya.paka@thermofisher.com
        - Key: costcenter
          Value: "400.8620.8582 : de platform"
        - Key: environment
          Value: nonprod
        - Key: project
          Value: cdcam
        - Key: division
          Value: digital engineering
        - Key: businessunit
          Value: corporate information technology
        - Key: snow_support
          Value: de.it.dev.registration
        - Key: group
          Value: corp
        - Key: group_beneficiary
          Value: corp
        - Key: compliance
          Value: n/a
        - Key: data_classification
          Value: internal use
  AccountUpdatedTopic:
    Type: AWS::SNS::Topic
    DeletionPolicy: Retain
    Properties:
      TopicName: !Sub cdcam-notify-account-updated-${Environments}
      Tags:
        - Key: name
          Value: cdcam
        - Key: application
          Value: cdcam
        - Key: app role
          Value: cdcam
        - Key: team name
          Value: armadillos
        - Key: application owner
          Value: vijaya.paka@thermofisher.com
        - Key: costcenter
          Value: "400.8620.8582 : de platform"
        - Key: environment
          Value: nonprod
        - Key: project
          Value: cdcam
        - Key: division
          Value: digital engineering
        - Key: businessunit
          Value: corporate information technology
        - Key: snow_support
          Value: de.it.dev.registration
        - Key: group
          Value: corp
        - Key: group_beneficiary
          Value: corp
        - Key: compliance
          Value: n/a
        - Key: data_classification
          Value: internal use
  PasswordResetTopic:
    Type: AWS::SNS::Topic
    DeletionPolicy: Retain
    Properties:
      TopicName: !Sub cdcam-password-reset-${Environments}
      Subscription:
        - Endpoint: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:tfgrp-pwd-reset-${Environments}
          Protocol: 'sqs'
      Tags:
        - Key: name
          Value: cdcam
        - Key: application
          Value: cdcam
        - Key: app role
          Value: cdcam
        - Key: team name
          Value: armadillos
        - Key: application owner
          Value: vijaya.paka@thermofisher.com
        - Key: costcenter
          Value: "400.8620.8582 : de platform"
        - Key: environment
          Value: nonprod
        - Key: project
          Value: cdcam
        - Key: division
          Value: digital engineering
        - Key: businessunit
          Value: corporate information technology
        - Key: snow_support
          Value: de.it.dev.registration
        - Key: group
          Value: corp
        - Key: group_beneficiary
          Value: corp
        - Key: compliance
          Value: n/a
        - Key: data_classification
          Value: internal use
  EmailServiceTopic:
    Type: AWS::SNS::Topic
    DeletionPolicy: Retain
    Properties:
      TopicName: !Sub cdcam-email-service-${Environments}
      Subscription:
        - Endpoint: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:tfgns-email-notification-${Environments}
          Protocol: 'sqs'
      Tags:
        - Key: name
          Value: cdcam
        - Key: application
          Value: cdcam
        - Key: app role
          Value: cdcam
        - Key: team name
          Value: armadillos
        - Key: application owner
          Value: vijaya.paka@thermofisher.com
        - Key: costcenter
          Value: "400.8620.8582 : de platform"
        - Key: environment
          Value: nonprod
        - Key: project
          Value: cdcam
        - Key: division
          Value: digital engineering
        - Key: businessunit
          Value: corporate information technology
        - Key: snow_support
          Value: de.it.dev.registration
        - Key: group
          Value: corp
        - Key: group_beneficiary
          Value: corp
        - Key: compliance
          Value: n/a
        - Key: data_classification
          Value: internal use
  NotifyAccountInfoTopic:
    Type: AWS::SNS::Topic
    DeletionPolicy: Retain
    Properties:
      TopicName: !Sub cdcam-notify-account-info-${Environments}
      Tags:
        - Key: name
          Value: cdcam
        - Key: application
          Value: cdcam
        - Key: app role
          Value: cdcam
        - Key: team name
          Value: armadillos
        - Key: application owner
          Value: vijaya.paka@thermofisher.com
        - Key: costcenter
          Value: "400.8620.8582 : de platform"
        - Key: environment
          Value: nonprod
        - Key: project
          Value: cdcam
        - Key: division
          Value: digital engineering
        - Key: businessunit
          Value: corporate information technology
        - Key: snow_support
          Value: de.it.dev.registration
        - Key: group
          Value: corp
        - Key: group_beneficiary
          Value: corp
        - Key: compliance
          Value: n/a
        - Key: data_classification
          Value: internal use
  AspireRegistrationTopic:
    Type: AWS::SNS::Topic
    DeletionPolicy: Retain
    Properties:
      TopicName: !Sub cdcam-aspire-registration-${Environments}
      Tags:
        - Key: name
          Value: cdcam
        - Key: application
          Value: cdcam
        - Key: app role
          Value: cdcam
        - Key: team name
          Value: armadillos
        - Key: application owner
          Value: vijaya.paka@thermofisher.com
        - Key: costcenter
          Value: "400.8620.8582 : de platform"
        - Key: environment
          Value: nonprod
        - Key: project
          Value: cdcam
        - Key: division
          Value: digital engineering
        - Key: businessunit
          Value: corporate information technology
        - Key: snow_support
          Value: de.it.dev.registration
        - Key: group
          Value: corp
        - Key: group_beneficiary
          Value: corp
        - Key: compliance
          Value: n/a
        - Key: data_classification
          Value: internal use
Parameters:
  Environments:
    Type: String
    Default: dev3
    AllowedValues:
      - dev3
      - qa1
      - qa4
      - qa3
      - qa5
      - stage
      - prod
    Description: Supported environments are dev3, qa1, qa4, qa3, qa5, stage and prod. Default is dev3.

Outputs:
  NotifyAccountInfoArn:
    Description: ARN of the Notify Account Info topic.
    Value: !Ref NotifyAccountInfoTopic
    Export:
      Name: !Sub "CdcamNotifyAccountInfo-TopicArn-${Environments}"