kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cdcam-role-view
  namespace: cdcam
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
