# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches:
      - integration/*
      - development/*
      - release/*
      - master

jobs:
  build:
    name: Build & Test Maven Project
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install -DskipTests --file pom.xml
    - name: Test with Maven
      run: mvn test
