name: Pull request merged
on:
  push:
    branches:
      - integration/**
jobs:
  configure-and-test:
    runs-on: [self-hosted]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Installs maven
        run: |
          curl -O https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
          tar xzvf apache-maven-3.8.6-bin.tar.gz

      - name: Build with Maven
        run: apache-maven-3.8.6/bin/mvn --batch-mode --update-snapshots test

      - name: Upload coverage report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results-report
          path: target/site/jacoco/
          if-no-files-found: error

  coverage-report-results:
    runs-on: [self-hosted]
    needs: configure-and-test
    environment: dev
    steps:
      - name: Parse coverage report results
        id: report
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/parse-coverage-report-results.js');
            script({ core });
          result-encoding: string

      - name: Build Teams comment
        id: comment
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/build-teams-comment.js');
            const results = ${{steps.report.outputs.objectResults}};
            script({ github, context, core, results });
          result-encoding: json

      - name: Post comment to Teams
        env:
          MS_TEAMS_INCOMING_WEBHOOK_URL: ${{ secrets.MS_TEAMS_INCOMING_WEBHOOK_URL }}
        run: |
          curl -H 'Content-Type: application/json' -d '${{steps.comment.outputs.comment}}' $MS_TEAMS_INCOMING_WEBHOOK_URL